[package]
name = "the_bor_patch"
version = "0.4.1"
authors = ["WuBoy and Bor"]
edition = "2018"

[package.metadata.skyline]
titleid = "01006A800016E000"

[lib]
crate-type = ["cdylib"]

[dependencies]
skyline = { git = "https://github.com/ultimate-research/skyline-rs.git" }
skyline_smash = { git = "https://github.com/ultimate-research/skyline-smash.git" }
acmd = { git = "https://github.com/ultimate-research/skyline-acmd.git" }

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"
lto = true
