[package]
name = "the_wubor_patch"
version = "0.15.0-dev"
authors = ["WuBoy and Bor"]
edition = "2018"

[package.metadata.skyline]
titleid = "01006A800016E000"

[lib]
crate-type = ["cdylib"]

[dependencies]
skyline = "0.2.1"
# skyline_smash = { git = "https://github.com/blu-dev/skyline-smash.git", features = ["weak_l2cvalue"] }
skyline_smash = { git = "https://github.com/blu-dev/skyline-smash.git", branch = "Specific-Skyline-Version", features = ["weak_l2cvalue"] }
# smash_script = { git = "https://github.com/blu-dev/smash-script.git", branch = "development" }
smash_script = { git = "https://github.com/blu-dev/smash-script.git", branch = "static-2-temp" }
# smashline = { git = "https://github.com/blu-dev/smashline.git", branch = "development" }
smashline = { git = "https://github.com/wuboyth/smashline.git", branch = "fixed-skyline" }
wubor_utils = { path = "./WuBor-Utils" }
custom_status = { path = "./custom-status" }
custom_var = { path = "./custom-var" }
# smash_rs = { package = "smash", git = "https://github.com/blu-dev/smash-rs" }
smash_rs = { package = "smash", git = "https://github.com/wuboyth/smash-rs" }
libc-nnsdk = "0.2.0"

[profile.dev]
panic = "abort"

[profile.release]
opt-level = 'z'
panic = "abort"
lto = true
codegen-units = 1
