name: Dev Build

on:
  push:
    branches: [ dev ]
  workflow_dispatch:

jobs:
  getversion:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.4.2
      - name: Get Plugin Version
        id: plugin_version
        # You may pin to the exact commit or the version.
        # uses: dante-signal31/rust-app-version@752c1afc51739ac75b36157cdd20e7116d203980
        uses: dante-signal31/rust-app-version@v1.0.0
    outputs:
      version: ${{ steps.plugin_version.outputs.app_version }}
  canceljob:
    runs-on: ubuntu-latest
    needs: getversion
    if: ${{ contains(needs.getversion.outputs.version, 'dev') != true }}
    steps:
      - name: Cancel Run if Version is not Dev
        uses: potiuk/cancel-workflow-runs@master
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          cancelMode: self
          selfPreservation: false
  plugin:
    runs-on: ubuntu-latest
    container:
      image: jugeeya/cargo-skyline:3.0.0-dkp-beta
    steps:
      - uses: actions/checkout@v2.4.2
      - name: Build release NRO
        run: |
          PATH=$PATH:/root/.cargo/bin:/opt/devkitpro/devkitA64/bin /root/.cargo/bin/cargo-skyline skyline build --release
        env:
          HOME: /root
      - name: Upload plugin artifact
        uses: actions/upload-artifact@v3.1.0
        with:
          name: plugin
          path: target/aarch64-skyline-switch/release/libthe_wubor_patch.nro
  upload:
    runs-on: ubuntu-latest
    needs: [ plugin, getversion ]
    steps:
      - uses: actions/checkout@v2.4.2
      - name: Download all artifacts
        uses: actions/download-artifact@v3.0.0
      - name: Download Assets
        # You may pin to the exact commit or the version.
        # uses: i3h/download-release-asset@6a9870c8f1c561f9e67550d6177c31c2b1c49fef
        uses: i3h/download-release-asset@v1.3.2
        with:
          # 
          owner: WuBoytH
          # 
          repo: WuBor-Romfs
          # 
          tag: dev
          # 
          file: romfs.zip
      - name: Update Release
        uses: meeDamian/github-release@2.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          prerelease: true
          allow_override: true
          gzip: false
          tag: ${{needs.getversion.outputs.version}}
          name: ${{needs.getversion.outputs.version}}
          body: >
            Nightly built off of the latest code in the dev branch.

            [You can view the changelogs for a specific version here.](https://drive.google.com/drive/folders/1yjnSZ5ZIBclAStsjJV1ODlBnJ3FYUaoD?usp=sharing)
            These will be updated to match the most recent dev build (this one!).
            
            ## Installation
            
            Remove the `ultimate/mods/The WuBor Patch` folder, if you have one already.

            Extract `romfs.zip` to the root of the SD card.

            Rename `libthe_wubor_patch.nro` file to `plugin.nro` and replace the one in `ultimate/mods/The WuBor Patch`.
          files: >
            plugin/*
            romfs.zip
