name: Rust

on:
  push:
    branches: [ dev ]
  workflow_dispatch:

jobs:
  plugin:
    runs-on: ubuntu-latest
    container:
      image: jugeeya/cargo-skyline:3.0.0-dkp-beta
    steps:
      - uses: actions/checkout@v2
      - name: Build release NRO
        run: |
          PATH=$PATH:/root/.cargo/bin:/opt/devkitpro/devkitA64/bin /root/.cargo/bin/cargo-skyline skyline build --release
        env:
          HOME: /root
      - name: Upload plugin artifact
        uses: actions/upload-artifact@v3.1.0
        with:
          name: plugin
          path: plugin
  upload:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/dev' && needs.plugin.status == 'success'
    needs:
      - plugin
    steps:
      - name: Download all artifacts
        uses: actions/download-artifact@v3.0.0
        with:
          name: plugin
      - name: Update Release
        uses: svenstaro/upload-release-action@2.3.0
        with:
          file: '*.nro'
          prerelease: true
          file_glob: true
          tag: nightly-dev
          release_name: nightly-dev
          body: >
            Beta built off of the latest code in the repository. 
            
            ## Installation
            
            Rename the file to plugin.nro and replace the one in `ultimate/mods/The WuBor Patch`.
