name: Rust Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    env:
      PLUGIN_NAME: The_WuBor_Patch
    runs-on: ubuntu-latest
    container: 
      image: jugeeya/cargo-skyline:2.1.0-dkp
    steps:
    - uses: actions/checkout@v2
    - name: Attempt to build
      run: PATH=$PATH:/usr/share/rust/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/bin cargo skyline build --release
# uncomment the build step below to build on every change to master.
#    - name: Update Release
#      env:
#          PLUGIN_NAME: 'libThe_Bor_Patch.nro'  #  change this to the name of your plugin
#      uses: meeDamian/github-release@2.0
#      with:
#        token: ${{ secrets.GITHUB_TOKEN }}
#        prerelease: true
#        allow_override: true
#        gzip: false
#        tag: master
#        name: master
#        body: Build of ${{env.PLUGIN_NAME}} from master.
#        files: >
#          ./target/aarch64-skyline-switch/release/${{env.PLUGIN_NAME}}
