name: Rust

on:
  push:
    branches: [ dev ]
  workflow_dispatch:

jobs:
  plugin:
    runs-on: ubuntu-latest
    container:
      image: jugeeya/cargo-skyline:3.0.0-dkp-beta
    steps:
      - uses: actions/checkout@v2
      - name: Build release NRO
        run: |
          PATH=$PATH:/root/.cargo/bin:/opt/devkitpro/devkitA64/bin /root/.cargo/bin/cargo-skyline skyline build --release
        env:
          HOME: /root
      - name: Upload plugin artifact
        uses: actions/upload-artifact@v2
        with:
          name: plugin
          path: target/aarch64-skyline-switch/release/libthe_wubor_patch.nro
  upload:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/dev' && needs.plugin.status == 'success'
    needs:
      - plugin
    steps:
      - name: Download all artifacts
        uses: actions/download-artifact@v2
      - name: Update Release
        uses: meeDamian/github-release@2.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          prerelease: true
          allow_override: true
          gzip: false
          tag: nightly-dev
          name: nightly-dev
          body: >
            Beta built off of the latest code in the repository. 
            
            ## Installation
            
            Rename the file to plugin.nro and replace the one in `ultimate/mods/The WuBor Patch`.
          files: >
            plugin/*
